pipeline {

    agent {
        docker {
            image 'python:2.7.16-slim'
        }
    }

    stages {
        stage('Build') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Compiling app'
                dir('vote') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('Test') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Running Unit tests'
                dir('vote') {
                    // sh 'npm install'
                    sh 'nosetests -v'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed successfully'
        }
    }
}
