pipeline {

    agent {
        docker {
            image 'maven:3.6.1-jdk-8-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage('Build') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit tests on worker app'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('docker-package') {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging worker app with docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1', 'credentials-id') {
                        def workerImage = docker.build("aniruth/worker:v${env.BUILD_ID}", "./worker")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed successfully'
        }
    }
}
